language: go
go:
  - 1.15
env:
  global:
    - CGO_ENABLED=0
gobuild_args: "-a -tags netgo -ldflags '-w'"
go_import_path: github.com/adevinta/vulcan-core-cli
install: _script/bootstrap
script: _script/cibuild
